---
name: Python Checks

on:
  workflow_call:
    inputs:
      pytest:
        required: false
        description: Run Python test suite using pytest
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  test:
    name: Test with Pytest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with pre-commit
        run: |
          python -m pip install pre_commit
          python -m pre_commit run --all-files
      - name: Test with pytest
        if: inputs.pytest
        run: |
          python -m pip install pytest
          python -m pytest -v tests/
