---
name: Rsync Deploy

on:
  workflow_call:
    inputs:
      rsync-delete:
        required: false
        description: Files on the target destination side to be deleted if they do not exist at the source.
        type: boolean
        default: false

    secrets:
      host:
        description: Host name of the remote machine
        required: true
      username:
        description: Username for login authorization to the host
        required: true
      target-directory:
        description: Target directory for rsync
        required: true
      ssh-key:
        description: Private SSH key for remote machine
        required: true

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy via rsync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.ssh-key }}
          known_hosts: "unnecessary"
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.host }} >> ~/.ssh/known_hosts
      - name: Determine Delete Flag
        uses: haya14busa/action-cond@v1
        id: rsync-delete-flag
        with:
          cond: ${{ inputs.rsync-delete }}
          if_true: '--delete'
          if_false: ''
      - name: Deploy with rsync
        run: rsync -avz ${{ steps.rsync-delete-flag.outputs.value }} . ${{ secrets.username }}@${{ secrets.host }}:${{ secrets.target-directory }}
